
# docker-compose.yml
```yml
version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-appuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apppass}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./infra
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./infra
      dockerfile: Dockerfile.frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app

  nginx:
    image: nginx:1.27
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
